Waku as a Network post
vacp2p/vac.dev pull request #105
Opened 2023-03-29 03:58 UTC by fryorcraken

This article aims to synthetize latest research and development that are shaping Waku as a network and provide a glimpse to the future.

I thought about writing the article last week but wasn't sure how useful it'd be. However, after the last scalability call, it seems to be needed.

Reviewers: Please do check veracity of statements in this article. If you feel I am asserting something that is still uncertain let me know. Thx!

2023-03-29 08:08 UTC, alrevuelta requested changes
Really nice post, left some comments.

I don't want to block the PR, but would love to use this to further discuss waku network future, and end up having a more extended post with the views of the whole team if thats fine.

Something that I would like to also cover in this post:
Required resources of waku nodes in terms of bandwitdth. Not for operators but for average end users of waku. Will I be able to run waku subscribed to a few communities in my laptop in Europe? And if I were in Africa? In order to answer this question, imho we have to come up with a max bandwidth that pubsub topics will use. I would say this is very important in the concept of "waku as a network".

2023-03-29 13:19 UTC, jm-clius approved these changes
I think this is a good overview. Thanks for writing it!

2023-03-30 03:47 UTC, fryorcraken commented on research/2023-04-02-waku-as-a-network.md
> +Waku does not intend to offer a free lunch. Ethereum's infrastructure relies on transaction fees, where users pay for
@alrevuelta good point on precision. Would there be an alternative phrasing that would enable a correct description of Ethereum while keeping it simple as explain Ethereum's compensation scheme is not really part of the goal of the post.

What about:

> Ethereum's infrastructure is supported by transaction fees and inflation, with validators receiving rewards from both sources.

2023-03-30 03:49 UTC, fryorcraken commented on research/2023-04-02-waku-as-a-network.md
> +Another perspective is to consider whether the Waku network will resemble Ethereum or Cosmos. We want Waku to be
> Then ofc mention that anyone is free to create their own network, just like Ethereum can have forks, but that are totally segregated from the main network.

Yes I hesitated whether to write more about private networks but opted against it for sake of conciseness. Will include for the sake of exactitude :)

2023-03-30 04:34 UTC, fryorcraken commented
Will continue tomorrow. One more TODO:

> Something that I would like to also cover in this post:
> Required resources of waku nodes in terms of bandwitdth. Not for operators but for average end users of waku. Will I be > able to run waku subscribed to a few communities in my laptop in Europe? And if I were in Africa? In order to answer this > question, imho we have to come up with a max bandwidth that pubsub topics will use. I would say this is very important in the concept of "waku as a network".

I am thinking about either adding an "open problem" section.

Or just add in the _Scalability and Discovery Protocols_ section that splitting the traffic does not mean tthere is a bandwitdh cap per shard, And hence, at this stage, we are not able to guarantee that someone using 4G or someone in Africa will be able to use the network.
I'll mention the case of the light client protocols.
Also probably good to mention the work we are doing:
- Status COmmunities protocol analysis to confirm efficient usage of Waku
- Kurtosis simulations to measure actual bandwitdh usage
- More sharding to segregate control messages.

I wonder if some QoS can be applied there? Could we separate "critical" control messages from "nice ux" ones?
Will probably leave that as an open questions and still mention it,

@alrevuelta if you have thoughts on these idea, please share. Otherwise will update and request new review.

2023-03-30 08:18 UTC, alrevuelta commented on research/2023-04-02-waku-as-a-network.md
> +Waku does not intend to offer a free lunch. Ethereum's infrastructure relies on transaction fees, where users pay for
yep, thats perfect.

2023-03-31 04:53 UTC, fryorcraken commented
> @fryorcraken
> 
> > I am thinking about either adding an "open problem" section.
> 
> Yep, thats fine. Lets put there the uncapped bandwidth. I'm actually planning some writeups in this area (not saying we should cap it) but on what to expect with different message sizes, shards, msg per second, etc. Related to [this](https://hackmd.io/IYmyyUIdSEuRZ7WbYd6dng?view) but from a different angle and stating the trilema Bandwidth/MsgRate/MsgSize. (leaving msg delay by now).

See https://github.com/vacp2p/vac.dev/pull/105/commits/3bdfc8ca6ca401aee78b796f0a7ea310593a514b

2023-04-03 04:08 UTC, merged

2023-04-05 00:33 UTC, fryorcraken commented
> LGTM :). I added an idea draft for Waku Products / Waku Network in the vac book: [here](https://github.com/vacp2p/vac-book/blob/main/scratch/waku_products_and_waku_network.md?rgh-link-date=2023-04-04T09%3A55%3A46Z)

Great.

Your write up looks good. I like the idea of being more detailed on what is possible.

May I suggest to park it for a month or two. Let's dogfood namedspace topics, have RLN testnet 3 under way or even close to completion and it'll be then a good opportunity to do a more detailed post on what the "heteregenous waku network" looks like "right now".

Happy to help or take over with the write up when we go for it.